server:
  port: 8090
  

spring:
  cloud:
    gateway:
      routes:
      - id: HelloService1
        uri: http://localhost:8088/
        predicates:
        - Path=/helloservice1/**
#        filters:
#        - CustomFilter
        
      - id: HelloService2
        uri: http://localhost:8089/
        predicates:
        - Path=/helloservice2/** 
#        filters:
#        - CustomFilter
